DROP TABLE IF EXISTS homeownersform;

CREATE TABLE homeownersform (
id INT(9) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(30),
Age VARCHAR(30),
Gender VARCHAR(50),
ResAddr VARCHAR(80),
LGAOrigin VARCHAR(50),
TelNo VARCHAR(13),
Email VARCHAR(20),
StaffNo VARCHAR(20),
StaffNoother VARCHAR(20),
WorkAddr VARCHAR(50),
RetirementYear VARCHAR(10),
Income VARCHAR(11),
maritalstat VARCHAR(100),
HomeOwnerStatus VARCHAR(30),
HomeType1 VARCHAR(30),
HomeType2 VARCHAR(30),
HomeType3 VARCHAR(30),
HomeType4 VARCHAR(30),
HomeType5 VARCHAR(30),
HomeType6 VARCHAR(30),
HomeType7 VARCHAR(30),
HomeType VARCHAR(30),
PaymentPower VARCHAR(30),
PaymentMode VARCHAR(30),
ServicingALoan VARCHAR(30),
CoperativeLoan VARCHAR(30),
CoperativeLoan1 VARCHAR(30),
GovernmentLoan VARCHAR(30),
InterestRate VARCHAR(30),
TenorofMortgage VARCHAR(30),
TimeonMortgage VARCHAR(30),
reg_date TIMESTAMP
);

DROP TABLE IF EXISTS homebuildersform;

CREATE TABLE homebuildersform (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
Parentcompany VARCHAR(100),
yearsinbusiness VARCHAR(100),
headquatersAddr VARCHAR(100),
contactperson VARCHAR(100),
phoneNumber VARCHAR(100),
email VARCHAR(100),
homeSpecs1 VARCHAR(100),
homeSpecs2 VARCHAR(100),
homeSpecs3 VARCHAR(100),
homeSpecs4 VARCHAR(100),
homeSpecs5 VARCHAR(100),
homeSpecs6 VARCHAR(100),
homeSpecs7 VARCHAR(100),
homeValueSpecs1 VARCHAR(100),
homeValueSpecs2 VARCHAR(100),
homeValueSpecs3 VARCHAR(100),
homeValueSpecs4 VARCHAR(100),
homeValueSpecs5 VARCHAR(100),
involvment VARCHAR(100),
involvmentSite VARCHAR(100),
involvmentPartners VARCHAR(100),
PmodeP VARCHAR(100),
MorgagePartners VARCHAR(100),
MorgagePartnersname VARCHAR(100),
eligibilityform1 VARCHAR(100),
eligibilityform2 VARCHAR(100),
eligibilityform3 VARCHAR(100),
eligibilityform4 VARCHAR(100),
eligibilityform5 VARCHAR(100),
eligibilityform6 VARCHAR(100),
eligibilityform7 VARCHAR(100),
capability VARCHAR(100),
typeofPart VARCHAR(100),
reg_date TIMESTAMP
);